version: '3'


#Docker Networks
networks:
  laravel-network:
    driver: bridge

services:
  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    tty: true
    ports:
      - "80:80"
    volumes:
      - ./htdocs:/var/www/html
      - ./docker/nginx/wishlist-service.roobeo.local-80.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
      - mysql
    networks:
      - laravel-network

  mysql:
    image: mysql:5.7.22
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel_user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: root
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
      - laravel-network
    volumes:
      - dbdata:/var/lib/mysql

  adminer:
    image: adminer
    restart: unless-stopped
    tty: true
    ports:
      - "8001:8080"
    networks:
      - laravel-network
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        user: www
        uid: 1000
    volumes:
      - ./htdocs:/var/www/html
      - ./docker/php/custom.ini:/usr/local/etc/php/conf.d/custom.ini
      - ./docker/php/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
    ports:
      - "9000:9000"
    networks:
      - laravel-network
volumes:
  dbdata: